apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: temalab
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.cicum.icu/temalab/frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: temalab
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: temalab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        - temalab.cicum.icu
      secretName: letsencrypt-frontend
  rules:
    - host: temalab.cicum.icu
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
