name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.cicum.icu
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.cicum.icu/temalab/frontend:latest
          file: ./deploy/Dockerfile
          context: "."
  deploy:
    runs-on: ubuntu-latest
    container: bitnami/kubectl:latest
    needs: build
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Load Kube Config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: mkdir -p /.kube && echo $KUBE_CONFIG > /.kube/config
      - name: Deploy
        run: kubectl apply -f ./deploy/app.yaml
